---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(Dependabot-docker): "
  - package-ecosystem: "docker"
    directory: "/splunk/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(Dependabot-docker): "
  - package-ecosystem: "docker"
    directory: "/kwok/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(Dependabot-docker): "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(Dependabot-actions): "
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(Dependabot-go): "
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(Dependabot-pip): "
